query Products(
  $where: ProductWhereInput
  $take: Int
  $orderBy: [ProductOrderByWithRelationInput!]
) {
  products(where: $where, take: $take, orderBy: $orderBy) {
    id
    name
    price
    categoryId
    imgURL
  }
}
